const $=s=>document.querySelector(s); const content=$('#content');
let token=localStorage.getItem('janecare_token'); let principal=null; let current=null;
async function api(path,opts={}){opts.headers={...(opts.headers||{})}; if(token) opts.headers.authorization=`Bearer ${token}`; const r=await fetch(path,opts); let data={}; try{data=await r.json()}catch{} if(r.status===401){logout(); throw new Error('Session expired or authentication required')} if(!r.ok) throw new Error(data.detail||'Request failed'); return data}
function card(label,value){return `<div class="card metric"><b>${value}</b><span>${label}</span></div>`}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const views={
 professional:[['professional','Professional'],['providers','Providers'],['government','Government']],
 admin:[['professional','Professional'],['providers','Providers'],['government','Government']],
 provider:[['providers','Provider Dashboard']], client:[['client','My Care']], government:[['government','Government']]
};
const titles={professional:['Professional Dashboard','Assigned cases, attention and accountable review'],providers:['Provider Network','Authorized referrals and service coordination'],client:['My JaneCare','Your case status and services'],government:['Government Gateway','Authorized reporting, validation and controlled submission']};
function renderNav(){const items=views[principal.role]||[]; $('#nav').innerHTML=items.map(([id,label])=>`<button data-view="${id}">${label}</button>`).join(''); document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>load(b.dataset.view)); current=items[0]?.[0]}
async function professional(){const [s,c]=await Promise.all([api('/api/dashboard/summary'),api('/api/cases')]); content.innerHTML=`<div class="security-banner">You are viewing only cases authorized for this professional account.</div><div class="grid">${card('Cases',s.cases)}${card('Urgent',s.urgent)}${card('Needs review',s.needs_review)}${card('Waiting',s.waiting)}<div class="card wide"><h3>Jane's Attention</h3>${s.attention.map(a=>`<div class="attention ${a.severity}">${escapeHtml(a.text)}</div>`).join('')}</div><div class="card full"><h3>Priority cases</h3><table><tr><th>Case</th><th>Client</th><th>Need</th><th>Priority</th><th>Status</th><th>Next action</th></tr>${c.map(x=>`<tr><td>${escapeHtml(x.id)}</td><td>${escapeHtml(x.client)}</td><td>${escapeHtml(x.need)}</td><td>${escapeHtml(x.priority)}</td><td><span class="pill">${escapeHtml(x.status)}</span></td><td>${escapeHtml(x.next_action)}</td></tr>`).join('')}</table></div></div>`}
async function providers(){const d=await api('/api/providers/dashboard'); content.innerHTML=`<div class="security-banner">Provider accounts see only referrals assigned to their organization.</div><div class="grid">${card('New referrals',d.counts.new)}${card('Active',d.counts.active)}${card('Information requested',d.counts.information_requested)}${card('Overdue',d.counts.overdue)}<div class="card full"><h3>Authorized referrals</h3><table><tr><th>Referral</th><th>Case</th><th>Provider</th><th>Service</th><th>Status</th><th>Due</th><th>Action</th></tr>${d.referrals.map(r=>`<tr><td>${escapeHtml(r.id)}</td><td>${escapeHtml(r.case_id)}</td><td>${escapeHtml(r.provider)}</td><td>${escapeHtml(r.service)}</td><td>${escapeHtml(r.status)}</td><td>${escapeHtml(r.due)}</td><td class="row-actions"><button class="action" onclick="providerAction('${r.id}','accept')">Accept</button><button class="action" onclick="providerAction('${r.id}','request-information')">Need info</button><button class="action" onclick="providerAction('${r.id}','complete')">Complete</button></td></tr>`).join('')}</table></div></div>`}
async function client(){const d=await api('/api/client/dashboard'); const c=d.case; content.innerHTML=`<div class="security-banner">This portal is scoped to your own JaneCare record.</div><div class="grid">${card('Case',escapeHtml(c.id))}${card('Priority',escapeHtml(c.priority))}${card('Status',escapeHtml(c.status))}<div class="card wide"><h3>What happens next</h3><p class="client-summary">${escapeHtml(c.next_action)}</p></div><div class="card full"><h3>Your services</h3><table><tr><th>Service</th><th>Status</th><th>Due</th></tr>${d.services.map(r=>`<tr><td>${escapeHtml(r.service)}</td><td>${escapeHtml(r.status)}</td><td>${escapeHtml(r.due)}</td></tr>`).join('')}</table></div></div>`}
async function government(){content.innerHTML=`<div class="security-banner">Government accounts are restricted to authorized reporting jurisdictions and do not receive unrestricted case access.</div><div class="grid"><div class="card wide"><h3>Government Gateway</h3><label>Period <input id="period" value="2026-08"></label> <label>Jurisdiction <select id="jurisdiction"><option>NL</option><option>BE</option><option>UK</option></select></label> <button class="action" onclick="prepareReport()">Prepare report</button><pre id="gov-result"></pre></div><div class="card wide"><h3>Authorization boundary</h3><p>Preparation and validation are separate from submission. Submission requires a government or administrator principal plus explicit accountable-human authorization.</p></div></div>`}
async function providerAction(id,action){await api(`/api/providers/referrals/${id}/${action}`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'}); providers()}
async function prepareReport(){try{const d=await api('/api/government/reports/prepare',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({period:$('#period').value,jurisdiction:$('#jurisdiction').value,standard:'generic'})}); const v=await api(`/api/government/reports/${d.id}/validate`,{method:'POST'}); $('#gov-result').textContent=JSON.stringify(v,null,2)}catch(e){$('#gov-result').textContent=e.message}}
async function load(v){current=v; document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v)); $('#title').textContent=titles[v][0]; $('#subtitle').textContent=titles[v][1]; try{await ({professional,providers,client,government}[v])()}catch(e){content.innerHTML=`<div class="card"><b>Error:</b> ${escapeHtml(e.message)}</div>`}}
function showApp(){ $('#login-screen').classList.add('hidden'); $('#app-shell').classList.remove('hidden'); $('#account-name').textContent=principal.name; $('#account-role').textContent=principal.role; $('#role-label').textContent=principal.role; renderNav(); load(current)}
function showLogin(){ $('#app-shell').classList.add('hidden'); $('#login-screen').classList.remove('hidden')}
function logout(){token=null; principal=null; localStorage.removeItem('janecare_token'); showLogin()}
$('#logout').onclick=logout; $('#refresh').onclick=()=>current&&load(current);
$('#login-form').onsubmit=async e=>{e.preventDefault(); $('#login-error').textContent=''; try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:$('#email').value,password:$('#password').value})}); const d=await r.json(); if(!r.ok) throw new Error(d.detail||'Sign in failed'); token=d.access_token; principal=d.principal; localStorage.setItem('janecare_token',token); showApp()}catch(err){$('#login-error').textContent=err.message}};
(async()=>{if(!token){showLogin();return} try{principal=await api('/api/auth/me');showApp()}catch{showLogin()}})();
